name: Publish Base Image

on:
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: "fsd-base-dev"
  IMAGE_REPO_PATH: "ghcr.io/${{github.repository_owner}}"
jobs:
  docker-build:
    strategy: 
      matrix:
        flavour: ["vanilla", "frontend"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: "Set tags in env"
        id: set-tags
        run: |
          source tags
          echo "PYTHON_FLASK_DEV_VANILLA=$PYTHON_FLASK_DEV" >> $GITHUB_ENV
          echo "PYTHON_FLASK_DEV_FRONTEND=$PYTHON_FLASK_DEV_FRONTEND" >> $GITHUB_ENV

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{env.IMAGE_REPO_PATH}}/${{env.IMAGE_NAME}}/${{matrix.flavour}}
          tags: |
            type=sha,format=long
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=${{env.PYTHON_FLASK_DEV_VANILLA}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=raw,value=${{env.PYTHON_FLASK_DEV_FRONTEND}},enable=(${{ (github.ref == format('refs/heads/{0}', 'main')) && (matrix.flavour == 'frontend') }})
            type=ref,event=branch

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.metadata.outputs.tags}}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
          file: ./python-flask-dev/Dockerfile